#############################################
# NETWORK
#############################################

bind 0.0.0.0
protected-mode no
port 6379

#############################################
# PERSISTENCE
#############################################

appendonly yes
appendfsync everysec

save 3600 1
save 300 100
save 60 10000

dir /data